feat: item requests, tests
babinpraktikum/java-shareit pull request #4
Opened 2022-09-18 11:13 UTC by babinpraktikum

2022-09-19 19:32 UTC, alexache requested changes

2022-09-19 19:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/impl/ItemRequestServiceImpl.java
> +        ItemRequest itemRequest = ItemRequestMapper.toItemRequest(requestDto);
Можно бы передавать время и юзера, как дополнительными аргументами в метод маппера

2022-09-19 19:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/requests/mapper/ItemRequestMapper.java
> +    private ItemRequestMapper() {
Зачем конструктор мапперу?

2022-09-19 19:32 UTC, alexache commented on src/test/java/ru/practicum/shareit/dataJPA/BookingStorageTest.java
> +class BookingStorageTest {
Не вижу тестов еще на ItemStorage, ItemRequestStorage

2022-09-19 19:32 UTC, alexache commented on src/test/java/ru/practicum/shareit/unit/request/GetAllRequestsByUserIdTest.java
> +class GetAllRequestsByUserIdTest {
Довольно странный способ написания тестов - зачем по отдельному классу на каждый юнит тест? Так не принято писать

2022-09-19 19:32 UTC, alexache commented on src/test/java/ru/practicum/shareit/webMVC/BookingControllerTest.java
> +    }
Можно еще добавлять метод verify от Mockito, чтобы проверять, что сервис был вызван и ожидаемое количество раз, как доп проверка корректности работы контроллера с сервисом

2022-09-19 19:32 UTC, alexache commented on src/test/java/ru/practicum/shareit/webMVC/BookingControllerTest.java
> +    ObjectMapper mapper;
Модификатор доступа

2022-09-19 19:32 UTC, alexache commented on src/test/java/ru/practicum/shareit/unit/booking/ApproveBookingTest.java
> +class ApproveBookingTest {
Из названия не очень понятно, на какой класс это тест, для юнит тестов - жто плохая практика. Очень хорошо бы понимать уже по названию какой класс этот тест тестирует

2022-09-19 19:38 UTC, babinpraktikum commented on src/main/java/ru/practicum/shareit/requests/mapper/ItemRequestMapper.java
> +    private ItemRequestMapper() {
для того, чтобы сообщить что объект создавать не нужно

2022-09-19 19:38 UTC, babinpraktikum commented on src/test/java/ru/practicum/shareit/dataJPA/BookingStorageTest.java
> +class BookingStorageTest {
ItemStorage не использует кастомных запросов, не вижу смысла тестировать эту функциональность

2022-09-20 18:39 UTC, alexache approved these changes

2022-09-21 14:49 UTC, merged